packages:
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'simple-git-hooks': false

catalog:
  '@eslint/compat': ^2.0.0
  '@rollup/plugin-replace': ^6.0.3
  '@stylistic/eslint-plugin': ^5.6.1
  '@tsconfig/node24': ^24.0.3
  '@types/jsdom': ^27.0.0
  '@types/node': ^24.10.4
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/eslint-plugin': ^1.6.5
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  copyfiles: ^2.4.1
  eslint: ^9.39.2
  eslint-plugin-vue: ~10.6.2
  jiti: ^2.6.1
  jsdom: ^27.3.0
  lint-staged: ^16.2.7
  npm-run-all2: ^8.0.4
  publint: ^0.3.16
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  typescript: ~5.9.3
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vitepress: ^1.6.4
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-tsc: ^3.2.1

cleanupUnusedCatalogs: true

dedupePeers: true

minimumReleaseAge: 1440
